mysql:
  host: 127.0.0.1
  port: 3306
  db: cinema_admin
  user: root
  password: 200301312934aA
  log_level: debug
  config: "charset=utf8&parseTime=True&loc=Local"
system:
  host: 127.0.0.1
  port: 8080
  env: release
logger:
  level: info
  prefix: 'cinema_admin'
  director: log
  show_line: true
  log_in_console: true