mysql:
  host: 127.0.0.1
  port: 3306
  db: cinema_admin
  user: root
  password: 200301312934aA
  log_level: debug
  config: "charset=utf8&parseTime=True&loc=Local"
system:
  host: 127.0.0.1
  port: 8080
  env: release
logger:
  level: info
  prefix: 'cinema_admin'
  director: log
  show_line: true
  log_in_console: true
jwt:
  secret_key: 1hwrmabS45PaYmDb
  expire_time: 2
  issuer: profikiller
redis:
  ip:
  port: 6379
  password:
  poolSize: 100
qi_niu:
  enable: true
  access_key: 1HlGSQlD_2sLtyRB9BlOTv7VibTfA48mXQ6zer8D
  secret_key: nz5nqqZjtHFtgCc8eQ6wLZurnEutTrB_7src69jl
  bucket: cinema-admin
  cdn: sbxaiblxv.hn-bkt.clouddn.com
  zone: z2
  size: 5